const allReportsList = [
    "Profit and Loss Detail",
    "Profit and Loss year-to-date comparison",
    "Quarterly Profit and Loss Summary",
    "Statement of Changes in Equity",
    "Custom Summary Report",
    "Project Profitability Summary",
    "Customer Balance Summary",
    "Customer Balance Detail",
    "Open Invoices",
    "Accounts receivable ageing detail",
    "Collections Report",
    "Invoice List",
    "Statement List",
    "Terms List",
    "Unbilled time",
    "Unbilled charges",
    "Sales by Customer Summary",
    "Sales by Customer Detail",
    "Sales by Product/Service Summary",
    "Sales by Product/Service Detail",
    "Product/Service List",
    "Income by Customer Summary",
    "Customer Contact List",
    "Payment Method List",
    "Transaction List by Customer",
    "Time Activities by Customer Detail",
    "Estimates by Customer",
    "Deposit Detail",
    "Bill Approval Status",
    "Product/Item Profitability by Customer",
    "Invoice Approval Status",
    "Transaction List by Tag Group",
    "Invoices and Received Payments",
    "Supplier Phone List",
    "Bills and Applied Payments",
    "Customer Phone List",
    "Purchases by Product/Service Detail",
    "Time Summary by Pay Type",
    "Timesheet Detail by Employee",
    "Tax Liability Report",
    "Adjusted Trial Balance",
    "Invalid Journal Transactions",
    "Profit and Loss By Tag Group",
    "Sales by Customer Type Detail",
    "Purchase List",
    "General Ledger List",
    "Purchases by Supplier Detail",
    "Audit Log",
    "Expenses by Supplier Summary",
    "Transaction List by Supplier",
    "Supplier Contact List",
    "Cheque Detail",
    "Accounts payable ageing summary",
    "Supplier Balance Detail",
    "Bill Payment List",
    "Accounts payable ageing detail",
    "Unpaid Bills",
    "Supplier Balance Summary",
    "Account List",
    "Reconciliation Reports",
    "Trial Balance",
    "Journal",
    "Profit and Loss",
    "Profit and Loss Comparison",
    "Balance Sheet",
    "Balance Sheet Comparison",
    "Transaction Detail by Account",
    "General Ledger",
    "Transaction List with Splits",
    "Statement of Cash Flows",
    "Transaction List by Date",
    "Recent Transactions",
    "Recurring Template List",
    "Time Activities by Employee Detail",
    "Recent/Edited Time Activities",
    "Employee Contact List",
    "Inventory Valuation Summary",
    "Inventory Valuation Detail",
    "Stock Take Worksheet",
    "Open Purchase Order Detail",
    "Open Purchase Order List",
    "Accounts receivable ageing summary",
    "Balance Sheet Detail",
    "Balance Sheet Summary",
    "Business Snapshot",
    "Profit and Loss as % of total income",
    "Profit and Loss by Customer",
    "Profit and Loss by Month"
];
