import React from 'react';
import { X } from 'lucide-react';

const HowWeUseAIModal = ({ isOpen, onClose }) => {
    if (!isOpen) return null;

    return (
        <div className="fixed inset-0 z-[10000] bg-slate-900/20 backdrop-blur-[1px] flex justify-end">
            <div className="bg-white shadow-2xl w-full max-w-[420px] flex flex-col h-full animate-in slide-in-from-right duration-300">
                <div className="flex items-center justify-end p-4 shrink-0">
                    <button 
                        onClick={onClose}
                        className="p-2 hover:bg-slate-100 rounded-full text-slate-500 transition-colors"
                    >
                        <X size={20} />
                    </button>
                </div>
                
                <div className="px-8 pb-8 overflow-y-auto flex flex-col gap-6 text-[13px] text-slate-700 leading-relaxed custom-scrollbar">
                    <h2 className="text-xl font-bold text-slate-800 mb-2">How's Onimta using AI?</h2>
                    <div>
                        <p className="mb-4">
                            We use AI to uncover insights, answer business-related questions, or propose work we can do for you.
                        </p>
                        <p>
                            We manage our own AI models and don't send your data to publicly accessible models. We train our AI as described in our <a href="#" className="text-[#0077c5] hover:underline font-medium border border-[#0077c5] px-1 rounded-sm">Global Privacy Statement</a>.
                        </p>
                    </div>

                    <div>
                        <h3 className="font-bold text-slate-800 text-[15px] mb-3">What you should know</h3>
                        <ul className="list-disc pl-5 flex flex-col gap-2">
                            <li>AI can do work for you, but you're always in control.</li>
                            <li>Onimta safeguards customer data and protects privacy using industry-leading technology and practices, and adheres to <a href="#" className="text-[#0077c5] hover:underline">Responsible AI Principles</a> and <a href="#" className="text-[#0077c5] hover:underline">Data Stewardship Principles</a>.</li>
                            <li>Human reviewers may provide quality assurance to improve accuracy on the answers you receive.</li>
                            <li>If you need extra help, have questions, or if something looks off, get in touch with human Onimta experts (fees may apply).</li>
                            <li>Some AI features may currently be in beta. Pricing, terms, conditions, special features, and service options are subject to change.</li>
                        </ul>
                    </div>

                    <div>
                        <h3 className="font-bold text-slate-800 text-[15px] mb-3">Remember</h3>
                        <ul className="list-disc pl-5 flex flex-col gap-2">
                            <li>You know your business best, so don't make important business or financial decisions based solely on answers generated by AI.</li>
                            <li>Remember to review all of your work, even if generated by AI, prior to sharing or sending. You are responsible for anything sent through our platform.</li>
                            <li>Don't rely on Onimta Intelligence Chat for legal, financial, or compliance decisions. Please confirm with a qualified professional as needed.</li>
                            <li>Some actions may require disclosures or terms not shown here. Please review in-product details before completing payments, bill pay, payroll, or lending tasks.</li>
                            <li>Feedback is key to improving AI. Tell us what you think.</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default HowWeUseAIModal;
